version: "3.7"
services:
  servico_db:
    image: postgres
    container_name: postgres-ctn
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  servico_server:
    build: "."
    container_name: python-ctn
    restart: always
    